version: "3"
services:
  reverse-proxy:
    container_name: nginx_reverse_proxy
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-reverse-proxy:latest
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - "80:80"
    networks:
      - reverse-proxy-network
  
networks:
  reverse-proxy-network: 
    name: reverse-proxy-network
    driver: bridge