version: "3"
services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - .env
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy-network
  
  # Certbot docs
  # https://hub.docker.com/r/certbot/certbot/   
  # https://eff-certbot.readthedocs.io/en/latest/install.html#running-with-docker
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot 
    command: "certonly --webroot -w /var/www/certbot --force-renewal -m ${EMAIL} -d ${DOMAIN} --agree-tos"


networks:
  reverse-proxy-network: 
    name: reverse-proxy-network
    driver: bridge