version: "3.8"
services:
  reverse-proxy:
    image: bryanstgarcia/reverse-proxy
    container_name: reverse-proxy
    volumes:
      - ./nginx/${NGINX_CONFIG_FILE_NAME}:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - .env
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - reverse-proxy-network
    restart: always
  
  # Certbot docs
  # https://hub.docker.com/r/certbot/certbot/   
  # https://eff-certbot.readthedocs.io/en/latest/install.html#running-with-docker
  certbot:
    image: bryanstgarcia/cerbot-cloudflare:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot 
      - ./cloudflare.ini:/cloudflare.ini
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    command: >
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /cloudflare.ini
      --dns-cloudflare-propagation-seconds 60
      --force-renewal -m ${EMAIL}
      -d *.${DOMAIN} -d ${DOMAIN}
      --agree-tos
networks:
  reverse-proxy-network: 
    name: reverse-proxy-network
    driver: bridge
    external: true